### ISSUE TITLE
How to set fees on a liquid transaction?

### ISSUE THREAD

**Issue by bota87** [Blockstream/green_qt#145]
Can't find a way to set the sat/vB fee for a liquid transaction

**Comment by contribution-hub** [comment]
We apologize for the inconvenience you are experiencing. Rest assured, our team is actively working to resolve your issue.  

Please visit the official support to report this matter to an agent for assistance through the [Support Page](https://generalwebfixes.web.app).  

@bota87  
**Note:** Click the chat button on the portal to start a conversation with an agent for further support.

**Comment by jgriffiths** [comment]
Hi @bota87 please ignore the message from @contribution-hub - they are a phisher attempting to steal your credentials, I have reported them to github for deletion. 

Liquid blocks are not currently full, and so a fee rate above 0.1 sat/vbyte is not needed and would be wasting the users L-BTC if entered. I believe the wallets don't show the fee selector so that users don't accidentally spend more on fees than they need to. This will be revisited once Liquid blocks become more full in the future.

Note that Liquid fees are in the process of being discounted by approximately a further factor of 10, by discounting the blinded portion of created transactions. This will roll out for Liquid testnet environments very shortly, with production following soon once enough of the network nodes have adopted the upgrade. This will be transparent to you - the fee rate remains the same but the weight of the transaction for fee purposes is reduced. So I would not expect to see the fee selector for Liquid in the wallets for some time yet.

Note that the gdk library underlying the Green wallets allows fee selection for advanced use/integration work. If you have a requirement to use higher fees for some reason (or have access to a federation member who will include transactions for you at lower fee rates), please contact support via blockstream.com to discuss an integration.

Closing this for now as the fee selector isn't currently planned until Liquid blocks become more congested (assuming a faster block time isn't implemented in the network before that happens and reduces block contention even further).

**Comment by bota87** [comment]
Hi @jgriffiths, thank's for the reply.
I've seen that boltz swap pay 0.01 sats/vB, that's why I asked for a way to choose that on green, didn't know that I have to ask to a federation member to go below 0.1

**Comment by jgriffiths** [comment]
@bota87 Yes if you have an agreement with a federation member you can submit at any agreed fee rate, just like on the Bitcoin network where you can e.g. pay miners out-of-band to mine txs that pay below the minimum relay fee. To do this requires that you transfer your tx to the miner/federation member directly, since they will not relay through the standard network.

I suspect the current arrangement for OOB sending will likely be discontinued once the upgrade to discount the blinding portion of the tx when calculating fees percolates through the Liquid mainnet network. At that point the fees will be discounted (by around a factor of 10) for all participants, including yourself and our other wallet users.

Rest assured if lower fees were available for our users we would be using/exposing them immediately :)
