### ISSUE TITLE
Can i decrypt timelocked transaction from green wallet using other methods? 

### ISSUE THREAD

**Issue by Fellane** [Blockstream/green_qt#42]
Green wallet sent me an encrypted file with locked time transaction. I know there is a method to decrypt it with garecovery. Is there any other method to decrypt this file using different software?

**Comment by jgriffiths** [comment]
The file format and its encryption are bespoke (double zipped AES-CBC encrypted with the chaincode of the main wallet bip32 key). So there are no general purpose tools available. If you are proficient in python you can take the decryption code from garecovery (function _unzip here: https://github.com/greenaddress/garecovery/blob/ff52848eb756e8f471d76f16e29d058978081e1f/gaservices/utils/gacommon.py#L18) in order to just decrypt the file.

If you have any issues with the recovery process please raise them on the garecovery repo at https://github.com/greenaddress/garecovery.
