### ISSUE TITLE
Fix connection issues-Jade

### ISSUE THREAD

**Issue by kloinka** [Blockstream/green_qt#50]
### Description

JADE connection via Green Linux AppImage

### Version

Release 0.1.0

### Steps to reproduce

connect Jade via USB as a non-root user

### Expected behaviour

connection to Jade

### Actual behaviour

Linux Wallet jade app wouldn't detect jade 
### Screenshots

NA

### Device or machine

Jade+Linux(Fedora33)

### Additional info
Linux detects the Jade
lsusb:
Bus 003 Device 007: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
But...
unless I run Blockstream Green as sudo it wont detect the Jade.
is there a udev rule for Jade's usb interface?

**Comment by domegabri** [comment]
Can you try adding the user to the dialout group? I think that should fix. Let me know if this works for you.

**Comment by kloinka** [comment]
That worked! 
but for Fedora:
If you try to add yourself to the dialout group it will fail. 
You have to:
Add the group manually
`grep ^dialout: /usr/lib/group |sudo tee -a /etc/group`
add current user to group
`sudo gpasswd -a ${USER} dialout`
activate that group
`newgrp dialout`
You may also need to log out and in to the GUI for app to work.

**Comment by mercurytoxic** [comment]
Since Archlinux doesn't use the dialout group the proper group as specified in [here](https://wiki.archlinux.org/title/Users_and_groups#Group_list) is **uucp**.
Add the current user to uucp
`sudo gpasswd -a ${USER} uucp`
To recognize the new group, If you don't want to log out and back in the user can use
`newgrp uucp`
