### ISSUE TITLE
Expected a difference in transaction fee

### ISSUE THREAD

**Issue by NotEternal** [Blockstream/green_qt#57]
### Expected behaviour

DIfference in the default fee options

### Actual behaviour

They aren't different

### Screenshots

![Screenshot 2021-08-15 03:02:23](https://user-images.githubusercontent.com/61930014/129471729-0a6971d5-d752-456e-98d5-bccece2c9c9e.png)

**Comment by jgriffiths** [comment]
Hi @NotEternal 

The mempool is currently almost empty and as a result, the mimimal possible fee of 1 satoshi per vbyte is currently suitable for any priority - 1 sat/vbyte transactions are clearing in the next block.

As the fee can't go lower than this, the fee rate is the same for all priorities. When the mempool gets more transactions you will see the rates change, with slower confirmation targets being cheaper.

Closing this issue as its expected behaviour under these conditions.
