### ISSUE TITLE
No ARM64 build for M1 Mac devices

### ISSUE THREAD

**Issue by grubles** [Blockstream/green_qt#73]
M1 Macs are pretty popular now. Currently there's only an x86_64 build though. Any plans for an ARM64 macOS build in the future?

**Comment by domegabri** [comment]
should be part of the next release

**Comment by grubles** [comment]
Awesome to hear! I suppose I can close this then.

**Comment by k0gen** [comment]
@grubles Please reopen or share a link for the Apple Silicon binary that I cannot find. 😘

**Comment by grubles** [comment]
Well I think at some point I realized it's actually a non-issue since M1 Macs have very fast x86_64 emulation. So I'm pretty sure you can just use the x86_64 binary.

**Comment by fulldecent** [comment]
This issue is a blocker for me and I hope it can be reopened.

Turning on emulation for Mac will degrade the computer. Specifically, it will install Rosetta 2, which can be slow and which will run silently without warning at various times.

Some people choose never to install Rosetta 2 for this reason—the random, invisible, unavoidable slowdowns.

Those people are now unable to run this software.
