### ISSUE TITLE
Confusing behavior when PIN is entered incorrectly

### ISSUE THREAD

**Issue by MarioGibney** [Blockstream/green_qt#8]
Ubuntu 18.04.3 LTS
Green 0.0.1

After entering one's PIN incorrectly, there is not option to log in to that wallet using mnemonic. The app will only display this page when that wallet is selected:

![Screenshot from 2020-02-21 17-54-53](https://user-images.githubusercontent.com/22239865/75084223-8ede7e00-54d3-11ea-8194-6e0be893405b.png)

It’s not frozen or anything, but there’s not option to enter my mnemonic from here instead. Seems a bit confusing and unclear.

Then when i go to restore it, it is listed as a new wallet on the app instead of the same  one. In this screenshot, all three bitcoin wallets are actually the same wallet:

![Screenshot from 2020-02-21 17-57-32](https://user-images.githubusercontent.com/22239865/75084235-a87fc580-54d3-11ea-8861-66f9391e992e.png)

**Comment by domegabri** [comment]
so you expect to have an option to restore once pin attempts are 0 (reasonable) but also don't restore the same wallet multiple times? at the moment you can restore the same wallet N times even without burning your pin attempts.

Implementing a restore policy means we leave out some edge cases (e.g. user forgets his pin, doesn't know he needs 3 wrong attempts to delete it and there's no delete wallet feature. App policy doesn't allow him to restore because there's already that wallet restored).

**Comment by MarioGibney** [comment]
I would expect one of these two things to happen:

- to be able to restore that listed wallet by having it ask for the mnemonic
- the app simply 'forgets' all about that wallet once the PIN has been entered 3 times incorrectly, and you have to restore it again

The second options seems cleaner, IMO.

The main thing that definitely needs fixing is that right now, any time you enter a PIN incorrectly three times, then you have a wallet listed there that you can never access (because entering that same wallet with a mnemonic will appear as a new wallet in that list).

**Comment by domegabri** [comment]
yes definitely needs to drop from the list wallets with no attempts left. And "no attempts left" view can lead to restore. Appreciate the feedback

**Comment by alessandro-saglimbeni** [comment]
fixed in 2234b4fa1a08f6a450268611f1101c861f3dfd30 closing
